name: Test
on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.23.x, 1.24.x]
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - run: go test ./...